name: monobank api tests
on: [push]
jobs:
  Monobank-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: test
      - run: echo {{secrets.MONOBANK_TOKEN}} >> .env
      - run: cargo test --verbose
